server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/security?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
#  security:
#    user:
#      name: test
#      password: 1234
